### ISSUE TITLE
Polyhedron.cpp // TODO: Do 2D convex hull.

### ISSUE THREAD

**Issue by aybe** [juj/MathGeoLib#52]
Hi @juj !

I've been using the OBB from your library for an editor I'm writing inside Unity, to get better bounds at what I'm actually picking in my editor:

![](https://raw.githubusercontent.com/aybe/MathGeoLib.Exports/master/sample-obb-unity.png)

So far it works well, except for flat objects. After debugging the code I found the following:

https://github.com/juj/MathGeoLib/blob/85ffab5f6a19bfff3fc3588d4f1656b2664ca19a/src/Geometry/Polyhedron.cpp#L1728

That explains why I'm getting infinite bounds and therefore why nothing is being drawn 😃.

__Question:__

Do you have any plans to implement a 2D convex hull in the near future ?

Alternatively, how do you have a rough idea on how it should be done ? I could give it a try then.

Thanks !!

**Comment by juj** [comment]
Thanks for querying. This was a long time todo, and did not have much interest in implementing handling for that case. Pushed in an implementation for this now in the above commit, and added a test for the planar case. I have not visualized this kind of scenario extensively in practice, so not sure how numerically float robust the implementation is - there may be some corner cases.

Basically the implementation detects if the input point set is planar so that either 3D convex hull computation fails, or the OBB computation fails, and then the common plane of the whole input point set is detected, and the point set projected flat to that common 2D plane, and a resulting OBB is constructed in that orientation. If you have point sets for which the computation fails badly, try building a test case with the tricky point set included (see the above commit for an example).

**Comment by aybe** [comment]
Thank you!

Should I find a case where it's not behaving as expected, I will open an issue about it.

Best Regards
